apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 692859947295.dkr.ecr.us-east-1.amazonaws.com/mushtaq/myapp:v2
        ports:
        - containerPort: 8000
